### ISSUE TITLE
document the process I'm using to derive new protobuf formats

### ISSUE THREAD

**Issue by dweinstein** [dweinstein/google-play-proto#1]

**Comment by BaseMax** [comment]
can you please share this ?
i am trying to get data from these paths but no luck 
https://android.clients.google.com/fdfe/homeV2
https://android.clients.google.com/fdfe/TopCharts

**Comment by dweinstein** [comment]
@hebrew878 I wrote a tool on top of JEB to extract the protobuf message formats from the application's nano protobuf structures by finding some patterns in the method body. This may have been a little bit easier with earlier versions of the play store. Folks can check out https://github.com/mmcloughlin/reprotobuf as it does something similar with androguard (haven't tested it myself). 

Your specific use I think requires reverse engineering the parts of the play store app that are talking to those endpoints. You might consider if the google-play-scraper, which doesn't require a device / device info, would work for your specific use case, see https://github.com/facundoolano/google-play-scraper#list which shows how to get at some of the data in the top charts that I assume you're looking for.

**Comment by dweinstein** [comment]
I haven't found the time to clean up the code but this is what I was using with JEB, https://gist.github.com/dweinstein/0960be45f2d0fe346151
