### ISSUE TITLE
Field 'appCategory' not fill

### ISSUE THREAD

**Issue by komeilkamal** [dweinstein/google-play-proto#3]
I'm using your proto file. it's work, but 'appCategory' in 'AppDetails' never fill. Please check it.
`repeated string appCategory = 7;`

**Comment by hister** [comment]
I have the same problem seems like google has removed that field from their data, I wonder where to take the category info from there is a field in annotations that has the category info in it has few Unicode character in it, 

example: 
```
annotations {
    53: "\n\004GAME\022\vGAME_ACTION"
}
```

**Comment by dweinstein** [comment]
google seemed to deprecate this field and its no longer reporting

**Comment by dweinstein** [comment]
See also https://github.com/dweinstein/node-google-play/issues/58

**Comment by dweinstein** [comment]
I did find another field where this data is now located -- its currently not a tagged field in this repo as I don't know what the new name is yet. I mentioned a workaround for now in the linked issue above in node gpapi

**Comment by komeilkamal** [comment]
Thanks for answer, How long it takes to add the new name and update repo?
